# This is the configuration used to check the rubocop source code.
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'

  TargetRubyVersion: 2.3

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  En  abled: false

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false
