sudo: required

services:
    - docker

language: ruby

rvm:
  - 2.2

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

script:
    - rake docker:test[test]
